services:
  test:
    image: pts/test-app
    expose:
      - 8080
    ports:
      - 8080:8080
  control:
    image: pts/control-node
    expose:
      - 8084
    ports:
      - 8084:8084
  worker:
    image: pts/worker-node
    ports:
      - 8083
    deploy:
      replicas: 5
      endpoint_mode: dnsrr